restaurant_menu = [
    "Margherita : Classic pizza with tomato sauce and mozzarella cheese : Veg : Veg Pizza : #vegan, #chefSpecial",
    "Margherita Extra : Margherita pizza with extra cheese and basil : Veg : Veg Pizza : #wantToRepeat",
    "Pepperoni : Pizza with tomato sauce, mozzarella, and pepperoni : Non-veg : Non-Veg Pizza : #spicy, #recommended",
    "BBQ Chicken : Pizza with barbecue sauce, chicken, and onions : Non-veg : Non-Veg Pizza : #specialtyChicken, #mealFor2",
    "Hawaiian Pizza : Pizza with tomato sauce, mozzarella, ham, and pineapple : Non-veg : NV Pizza : #new, #recommended",
    "Caesar Salad : Romaine lettuce, croutons, Parmesan cheese, Caesar dressing : Veg : Specialty : #dairyFree, #wantToRepeat",
    "Caprese Salad : Fresh mozzarella, tomato, and basil drizzled with balsamic : Veg : Specialty : #wantToRepeat, #dairyFree",
    "Greek Salad : Lettuce, tomato, cucumber, feta cheese, and Kalamata olives : Veg : Specialty : #wantToRepeat, #dairyFree, #glutenFree",
    "Tandoori Chicken : Chicken marinated in Indian spices and grilled : Non-veg : Specialty : #spicy, #recommended, #new",
    "Chicken Alfredo : Fettuccine with creamy Alfredo sauce and chicken : Non-veg : Meals and combos : #containsDairy, #mealFor2",
    "Vegan Burger : Plant-based burger patty with lettuce, tomato, and onion : Veg : Meals and combos : #guiltFree, #vegan, #mealFor2",
    "Garlic Bread : Sliced baguette with garlic butter and Parmesan : Veg : Sides : #new, #sides",
    "Buffalo Wings : Deep-fried chicken wings served with hot sauce and blue cheese : Non-veg : Sides : #spicy, #sides,#specialtyChicken, #new",
]
